<?php

// autoload-classmap.php @generated by Strauss

$strauss_src = dirname(__FILE__);

return array(
   'EverAccounting\ByteKit\Plugin' => $strauss_src . '/byteever/bytekit-plugin/src/Plugin.php',
   'EverAccounting\ByteKit\Scripts' => $strauss_src . '/byteever/bytekit-plugin/src/Scripts.php',
   'EverAccounting\ByteKit\Interfaces\Pluginable' => $strauss_src . '/byteever/bytekit-plugin/src/Interfaces/Pluginable.php',
   'EverAccounting\ByteKit\Interfaces\Scriptable' => $strauss_src . '/byteever/bytekit-plugin/src/Interfaces/Scriptable.php',
   'EverAccounting\ByteKit\Admin\Notices' => $strauss_src . '/byteever/bytekit-plugin/src/Admin/Notices.php',
   'EverAccounting\ByteKit\Admin\Flash' => $strauss_src . '/byteever/bytekit-plugin/src/Admin/Flash.php',
   'EverAccounting\ByteKit\Services' => $strauss_src . '/byteever/bytekit-plugin/src/Services.php',
   'EverAccounting\ByteKit\Traits\HasPlugin' => $strauss_src . '/byteever/bytekit-plugin/src/Traits/HasPlugin.php',
   'EverAccounting\ByteKit\Models\Post' => $strauss_src . '/byteever/bytekit-models/src/Post.php',
   'EverAccounting\ByteKit\Models\Model' => $strauss_src . '/byteever/bytekit-models/src/Model.php',
   'EverAccounting\ByteKit\Models\Relations\Relation' => $strauss_src . '/byteever/bytekit-models/src/Relations/Relation.php',
   'EverAccounting\ByteKit\Models\Relations\HasMany' => $strauss_src . '/byteever/bytekit-models/src/Relations/HasMany.php',
   'EverAccounting\ByteKit\Models\Relations\BelongsToMany' => $strauss_src . '/byteever/bytekit-models/src/Relations/BelongsToMany.php',
   'EverAccounting\ByteKit\Models\Relations\HasOne' => $strauss_src . '/byteever/bytekit-models/src/Relations/HasOne.php',
   'EverAccounting\ByteKit\Models\Relations\BelongsTo' => $strauss_src . '/byteever/bytekit-models/src/Relations/BelongsTo.php',
   'EverAccounting\ByteKit\Models\Query' => $strauss_src . '/byteever/bytekit-models/src/Query.php',
   'EverAccounting\ByteKit\Models\Traits\HasMetaData' => $strauss_src . '/byteever/bytekit-models/src/Traits/HasMetaData.php',
   'EverAccounting\ByteKit\Models\Traits\HasRelations' => $strauss_src . '/byteever/bytekit-models/src/Traits/HasRelations.php',
   'EverAccounting\ByteKit\Models\Traits\HasAttributes' => $strauss_src . '/byteever/bytekit-models/src/Traits/HasAttributes.php',
);