<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'EverAccounting\\ByteKit\\Models\\' => array($vendorDir . '/byteever/bytekit-models/src'),
    'EverAccounting\\ByteKit\\' => array($vendorDir . '/byteever/bytekit-plugin/src'),
    'EverAccounting\\' => array($baseDir . '/includes'),
);
