<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInita4e4f3e1cb6f4a6814b4c9b04f340617
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('EverAccounting\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \EverAccounting\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInita4e4f3e1cb6f4a6814b4c9b04f340617', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \EverAccounting\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInita4e4f3e1cb6f4a6814b4c9b04f340617', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\EverAccounting\Composer\Autoload\ComposerStaticInita4e4f3e1cb6f4a6814b4c9b04f340617::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
